### ISSUE TITLE
tcl transient errors

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/k4SimDelphes#55]
Running 
```DelphesPythia8EvtGen_EDM4HEP_k4Interface```

like

```DelphesPythia8EvtGen_EDM4HEP_k4Interface card.tcl edm4hep2.tcl card.cmd events_049762078.root DECAY.DEC evt.pdl user.dec 5122 Lb_SIGNAL 1```

with the files in 

```/afs/cern.ch/user/h/helsens/public/4Thomas/testjob/```

it often produces an error that it can not read the tcl, and more rarely a seg fault [2].

This occur ONLY with this EvtGen ```user.dec``` (or at least out of all the ones I tried, it's the only one)

As EvtGen parse the files before the tcl, it could be a left over from EvtGen that resurfaces in k4SimDelphes.

[1] Error
```
** ERROR: can't read configuration file edm4hep2.tcl
missing close-bracket
```

[2] Stack trace
```
===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007fcc413094fc in waitpid () from /lib64/libc.so.6
#1  0x00007fcc41286f62 in do_system () from /lib64/libc.so.6
#2  0x00007fcc423b9293 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x18f1390) at /tmp/gitlab-runner/spack-stage/spack-stage-root-6.24.00-u7xb6dwwdgx7v3xbdg37tsfvdufauaef/spack-src/core/unix/src/TUnixSystem.cxx:2120
#3  TUnixSystem::StackTrace (this=0x18f1390) at /tmp/gitlab-runner/spack-stage/spack-stage-root-6.24.00-u7xb6dwwdgx7v3xbdg37tsfvdufauaef/spack-src/core/unix/src/TUnixSystem.cxx:2411
#4  0x00007fcc423bbbb5 in TUnixSystem::DispatchSignals (this=0x18f1390, sig=kSigSegmentationViolation) at /tmp/gitlab-runner/spack-stage/spack-stage-root-6.24.00-u7xb6dwwdgx7v3xbdg37tsfvdufauaef/spack-src/core/unix/src/TUnixSystem.cxx:3649
#5  <signal handler called>
#6  0x00007fcc465a7fe4 in CompileBraces.isra.4 () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#7  0x00007fcc465a9e39 in TclCompileString () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#8  0x00007fcc465aae22 in SetByteCodeFromAny () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#9  0x00007fcc4659c21d in Tcl_EvalObj () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#10 0x00007fcc4649bb5d in ExRootConfReader::ReadFile(char const*, bool) () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#11 0x000000000043ac34 in int doit<podio::ROOTWriter>(int, char**, DelphesInputReader&) ()
#12 0x0000000000418482 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007fcc465a7fe4 in CompileBraces.isra.4 () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#7  0x00007fcc465a9e39 in TclCompileString () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#8  0x00007fcc465aae22 in SetByteCodeFromAny () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#9  0x00007fcc4659c21d in Tcl_EvalObj () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#10 0x00007fcc4649bb5d in ExRootConfReader::ReadFile(char const*, bool) () from /cvmfs/sw.hsf.org/spackages2/delphes/3.4.3pre10/x86_64-centos7-gcc8.3.0-opt/otxgijra3aldmleuxl4bwakvrbk2gzhu/lib/libDelphes.so
#11 0x000000000043ac34 in int doit<podio::ROOTWriter>(int, char**, DelphesInputReader&) ()
#12 0x0000000000418482 in main ()
===========================================================
```

**Comment by tmadlener** [comment]
@clementhelsens I think this can be closed now, because the space changes are in the current master, right?

**Comment by clementhelsens** [comment]
indeed!
